/*
 * ddm_cup.ino — La Quiniela betting cup (ESP-NOW bench test)
 *
 * ESP32-2432S028R ("Cheap Yellow Display") as the horse-number display for
 * the DDM Live Betting System betting cups (DDM 2027).
 *
 * Derived from ddm_cyd_prototype.ino. The display pipeline — traced-outline
 * glyph fill, blend565 anti-aliasing, drawNumber condensing, saddle cloth
 * table, backlight LEDC handling, pin defines — is carried over from the
 * prototype and validated on hardware. Since 2026-09-17 every string, not
 * just the digits, is drawn through that renderer with the Impact glyph set
 * in ddm_font.h (uppercase only); the Adafruit bitmap fonts are gone. The
 * mode state machine renders whatever the gateway broadcasts over ESP-NOW.
 *
 * ===========================================================================
 * THREE FILES. All must sit in this folder:
 *     ddm_cup.ino       <- this file
 *     ddm_font.h        <- traced Impact glyphs (GENERATED by tools/tracefont.py — do not edit)
 *     ddm_common.h      <- symlink to ../ddm_common.h (see ../README.md)
 * ===========================================================================
 *
 * LIBRARIES (Tools -> Manage Libraries):  Adafruit GFX Library,
 * Adafruit ILI9341, HX711 Arduino Library (Bogdan Necula / bogde). Say
 * Install All if it offers dependencies.
 *
 * BOARD:  ESP32 Dev Module
 *
 * UPLOADING:  hold BOOT, click Upload, keep holding until the log names the
 * chip, then let go.
 *
 * CONTROLS — BOOT button:
 *     Short press  ->  toggle the diagnostic overlay (RSSI, drops, seq, age,
 *                      tokens and net scale counts)
 *     Hold 3 s     ->  re-tare the scale: count back to 0, green LED blinks
 *     Hold 15 s    ->  (keep holding well past the tare) step the display
 *                      orientation to the next of its four settings and
 *                      save it in NVS for this cup
 *
 * SERIAL (115200):  o = next orientation,  h = mirror left-right,
 *                   v = mirror top-bottom (all saved),  x = forget the saved
 *                   orientation (back to the panel-ID default),  t = tare,
 *                   c<N> = N tokens are on the plate: calibrate counts/token
 *                   for this cup and save it (c0 forgets it),  s = apply the
 *                   settled load to the count now,  ? = help
 *
 * Until the gateway assigns this cup an ID, the screen shows this board's
 * own MAC address in large text — that is how the four MACs get collected
 * for the gateway's KNOWN_CUPS[] table with no serial cable.
 *
 * SCALE: an HX711 on CN1 (DT GPIO27, SCK GPIO22) weighs the tokens. Counting
 * is by steps against a slow-tracking baseline, never by absolute weight; the
 * two calibration constants in the tunables came from tools/hx711_calibrate/.
 * The cup never shows the count on a normal screen (the splash display does);
 * the diagnostic overlay shows TOKENS and the net counts for bench checks, and
 * telemetry carries rawWeight (reading minus tare) and tokenCount.
 */

#include <SPI.h>
#include <Adafruit_GFX.h>
#include <Adafruit_ILI9341.h>
#include <HX711.h>
#include <WiFi.h>
#include <esp_now.h>
#include <esp_wifi.h>
#include <Preferences.h>
#include "ddm_font.h"
#include "ddm_common.h"

// ===========================================================================
// Tunables
// ===========================================================================
#define ORIENT_DEFAULT      0xC0  // MADCTL MX|MY bits for a cup with nothing saved: Board A's batch (RDDID 10 81 B3)
#define ORIENT_DEFAULT_ID00 0x40  // same for the batch whose RDDID reads 00 00 00 (the scale cup, 2026-09-15): MX alone
#define INVERT     false        // true if colors come out backwards

#define TRACK       0.06f       // extra gap between two digits on top of the Impact advance, as a fraction of height
#define CONDENSE    0.72f       // narrowest a digit may be squeezed (1.0 = never)
#define SUBROWS        4        // vertical anti-alias samples per pixel row

// Link + render timing
#define HELLO_MS          1000  // hello cadence until the gateway answers
#define TELEMETRY_MS      2000  // telemetry cadence once assigned
#define LINK_TIMEOUT_MS  10000  // no gateway packet this long -> NO LINK badge
#define SCRATCH_FLASH_MS  1200  // scratched alternation period
#define PODIUM_STEP_MS    2000  // podium metal cycle period (from prototype)
#define OVERLAY_MS         500  // diagnostic overlay refresh

// ---------------------------------------------------------------------------
// Scale — HX711 on CN1. CALIBRATION CONSTANTS: measured on the bench with
// tools/hx711_calibrate/ (ten tokens of the current print dropped one at a
// time; mean step 6212 counts, sd 102 = 1.6%). If the token print changes,
// re-run that tool and paste its two #define lines over these.
// ---------------------------------------------------------------------------
#define COUNTS_PER_TOKEN   6212L    // mean step, 10 tokens, sd 102 (1.6%): the default until a cup is calibrated (serial c<N>)
#define TOKEN_THRESHOLD    3106L    // half a token (a calibrated cup derives its own from its counts/token)

#define HX711_DT                27  // CN1 data
#define HX711_SCK               22  // CN1 clock
#define SCALE_WARMUP_MS      30000  // HX711 drifts after power-up: no tare, no counting until this has passed
#define SCALE_TARE_SAMPLES      30  // averaged for the tare (~3 s at 10 SPS)
#define SCALE_BASELINE_TAU_MS 5000  // time constant of the slow baseline that absorbs drift and relaxation...
#define SCALE_FAST_TAU_MS     1500  // ...and a faster one for SCALE_POST_EVENT_MS after a drop, while the stack relaxes
#define SCALE_POST_EVENT_MS  15000  // how long a stack keeps relaxing after an impact (bench: 10-15 s)
#define SCALE_CONFIRM_SAMPLES    3  // consecutive samples past the threshold that make a drop/remove event
#define OVERSHOOT_PCT         2.0f  // impact overshoot taken off a drop's step, as % of the load already on the plate (bench: 1.4-2.5%)
#define SETTLE_RING             20  // samples (~2 s) that must be flat before the settled load is trusted
#define SETTLE_SPREAD         1200  // max-min over those samples that still counts as flat (idle noise is far below)
#define SETTLE_AMBIGUOUS     0.35f  // settled load within this many tokens of a half: leave the count alone
#define SETTLE_MAX_FIX           1  // a settle check may move the count by at most this many tokens; a bigger
                                    // disagreement is only reported (serial s applies it). Raise it once the scale
                                    // base is proven free of hysteresis (bench 2026-09-15: the same 50 tokens
                                    // settled at 50.6, 53.2 and 51.5 tokens as the cup was shaken)
#define TARE_HOLD_MS          3000  // BOOT held this long re-tares
#define ORIENT_HOLD_MS       15000  // BOOT kept held this long steps the display orientation (saved); far past
                                    // the 3 s tare so a long tare press cannot rotate a cup by accident
#define TARE_BLINK_MS          150  // LED acknowledgement of a manual tare

// ---------------------------------------------------------------------------
// CYD hardware pins — correct for the ESP32-2432S028R, leave alone
// ---------------------------------------------------------------------------
#define TFT_MISO  12
#define TFT_MOSI  13
#define TFT_SCLK  14
#define TFT_CS    15
#define TFT_DC     2
#define TFT_RST   -1
#define TFT_BL    21

#define BOOT_BTN   0
#define LED_R      4
#define LED_G     16
#define LED_B     17

Adafruit_ILI9341 tft = Adafruit_ILI9341(TFT_CS, TFT_DC, TFT_RST);

Preferences prefs;                     // NVS: per-cup settings that survive reflashing
uint8_t     orientFlips = ORIENT_DEFAULT;  // MADCTL MX (0x40) | MY (0x80) bits, loaded from NVS at boot

// ---------------------------------------------------------------------------
#define RGB(r,g,b) ((uint16_t)((((r) & 0xF8) << 8) | (((g) & 0xFC) << 3) | ((b) >> 3)))

#define C_BLACK   RGB(0x00,0x00,0x00)
#define C_WHITE   RGB(0xFF,0xFF,0xFF)
#define C_RED     RGB(0xE3,0x18,0x37)
#define C_GOLD    RGB(0xFF,0xD7,0x00)
#define C_SILVER  RGB(0xC0,0xC0,0xC8)
#define C_BRONZE  RGB(0xCD,0x7F,0x32)
#define C_DIM     RGB(0x50,0x50,0x50)
#define C_AMBER   RGB(0xD4,0xA0,0x00)

struct Cloth { uint16_t bg; uint16_t fg; };

Cloth cloth(uint8_t n) {
  switch (n) {
    case 1:  return { RGB(0xE3,0x18,0x37), C_WHITE };
    case 2:  return { C_WHITE,             C_BLACK };
    case 3:  return { RGB(0x00,0x33,0xA0), C_WHITE };
    case 4:  return { RGB(0xFF,0xCD,0x00), C_BLACK };
    case 5:  return { RGB(0x00,0x84,0x3D), C_WHITE };
    case 6:  return { C_BLACK,             RGB(0xFF,0xD7,0x00) };
    case 7:  return { RGB(0xFF,0x66,0x00), C_BLACK };
    case 8:  return { RGB(0xFF,0x69,0xB4), C_BLACK };
    case 9:  return { RGB(0x40,0xE0,0xD0), C_BLACK };
    case 10: return { RGB(0x66,0x33,0x99), C_WHITE };
    case 11: return { RGB(0x80,0x80,0x80), RGB(0xE3,0x18,0x37) };
    case 12: return { RGB(0x32,0xCD,0x32), C_BLACK };
    case 13: return { RGB(0x8B,0x45,0x13), C_WHITE };
    case 14: return { RGB(0x80,0x00,0x00), RGB(0xFF,0xCD,0x00) };
    case 15: return { RGB(0xC4,0xB7,0xA6), C_BLACK };
    case 16: return { RGB(0x87,0xCE,0xEB), RGB(0xE3,0x18,0x37) };
    case 17: return { RGB(0x00,0x00,0x80), C_WHITE };
    case 18: return { RGB(0x22,0x8B,0x22), RGB(0xFF,0xCD,0x00) };
    case 19: return { RGB(0x00,0x00,0x8B), RGB(0xE3,0x18,0x37) };
    case 20: return { RGB(0xFF,0x00,0xFF), RGB(0xFF,0xCD,0x00) };
    default: return { RGB(0x80,0x80,0x80), C_WHITE };
  }
}

int SW, SH;

// ===========================================================================
// TEXT — every string on the cup goes through the traced-outline renderer
// with the Impact glyph set in ddm_font.h: 0-9 A-Z space % : - . ! ? /,
// uppercase only. Layout is advance-based, no kerning. In a glyph, y = 0 is
// the cap-height line and y = FONT_GRID the baseline; round glyphs overshoot
// both by a few units and are drawn, not clipped. Text is anti-aliased
// against the colour passed as bg, so every call must pass what is really
// behind it; centerText uses textBg, which each screen sets after its fill.
// ===========================================================================
#define TEXT_CAP_MAX  34        // centerText's default cap-height ceiling, about the old 24pt face
#define TEXT_CAP_MIN   8        // never smaller than this; the string just runs wide

uint16_t textBg = C_BLACK;      // what centerText blends against; set by each screen after its fill

// Glyph table index for c. Anything the font lacks maps to '?', which the
// caller draws as a gap of that width instead of a glyph.
static int fontGlyph(char c, bool* known) {
  int i = fontIndex(c);
  if (known) *known = (i >= 0);
  return i >= 0 ? i : fontIndex('?');
}

// Width of s in pixels at that cap height and condense factor.
int textWidth(const char* s, int capPx, float condense) {
  float sx = (float)capPx / FONT_GRID * condense;
  float w  = 0;
  for (; *s; s++) w += FONT_ADV[fontGlyph(*s, nullptr)] * sx;
  return (int)ceilf(w);
}
int textWidth(const char* s, int capPx) { return textWidth(s, capPx, 1.0f); }

// Centre s horizontally on cx. capTop is the y of the cap-height line, capPx
// the cap height in pixels. condense < 1.0 narrows the glyphs.
void drawText(const char* s, int cx, int capTop, int capPx,
              uint16_t fg, uint16_t bg, float condense) {
  float sy = (float)capPx / FONT_GRID;
  float sx = sy * condense;
  float x  = cx - textWidth(s, capPx, condense) * 0.5f;
  for (; *s; s++) {
    bool known;
    int  gi = fontGlyph(*s, &known);
    if (known && FONT_NCONT[gi] > 0) fillGlyph(gi, x, (float)capTop, sx, sy, fg, bg);
    x += FONT_ADV[gi] * sx;
  }
}
void drawText(const char* s, int cx, int capTop, int capPx, uint16_t fg, uint16_t bg) {
  drawText(s, cx, capTop, capPx, fg, bg, 1.0f);
}

// Same, from a left edge (overlay lines).
void drawTextLeft(const char* s, int x, int capTop, int capPx, uint16_t fg, uint16_t bg) {
  drawText(s, x + textWidth(s, capPx, 1.0f) / 2, capTop, capPx, fg, bg, 1.0f);
}

// Largest cap height up to capMax at which s fits maxW, drawn so that cy is
// the vertical middle of the caps, which is where the old Adafruit version
// put the middle of its text bounds. Width is linear in the cap height, so
// the fit is a division, not a search.
void centerTextCap(const char* s, int cx, int cy, int maxW, uint16_t fg, int capMax) {
  long adv = 0;
  for (const char* p = s; *p; p++) adv += FONT_ADV[fontGlyph(*p, nullptr)];
  int cap = capMax;
  if (adv > 0) {
    long fit = (long)maxW * FONT_GRID / adv;
    if (fit < cap) cap = (int)fit;
  }
  if (cap < TEXT_CAP_MIN) cap = TEXT_CAP_MIN;
  drawText(s, cx, cy - cap / 2, cap, fg, textBg, 1.0f);
}

void centerText(const char* s, int cx, int cy, int maxW, uint16_t fg) {
  centerTextCap(s, cx, cy, maxW, fg, TEXT_CAP_MAX);
}

// ===========================================================================
// GLYPH FILL
//
// Even-odd scanline fill of the traced outlines, supersampled vertically and
// with fractional horizontal coverage, blended against the background color.
// Proven on both panel batches. The only change for the Impact set is that
// the pixel box comes from the glyph's own contour points, so overshoots and
// overhangs (round shapes, J, /) are drawn rather than clipped at the advance.
// ===========================================================================
static uint16_t rowBuf[340];
static uint8_t  cov[340];

static inline uint16_t blend565(uint16_t fg, uint16_t bg, uint16_t a) {
  uint16_t fr = (fg >> 11) & 0x1F, fgn = (fg >> 5) & 0x3F, fb = fg & 0x1F;
  uint16_t br = (bg >> 11) & 0x1F, bgn = (bg >> 5) & 0x3F, bb = bg & 0x1F;
  uint16_t r = (fr * a + br * (255 - a)) / 255;
  uint16_t g = (fgn * a + bgn * (255 - a)) / 255;
  uint16_t b = (fb * a + bb * (255 - a)) / 255;
  return (r << 11) | (g << 5) | b;
}

// One glyph of ddm_font.h: grid units mapped to pixels with (ox, oy) at the
// glyph origin (x = 0, cap-height line) and scale (sx, sy).
static void fillGlyph(int gi, float ox, float oy, float sx, float sy,
                      uint16_t fg, uint16_t bg) {
  uint16_t first = FONT_FIRST[gi];
  uint8_t  nc    = FONT_NCONT[gi];
  if (nc == 0) return;                        // space: advance only

  // Pixel box from the contour points themselves, not the advance width.
  int16_t gxLo = 32767, gxHi = -32768, gyLo = 32767, gyHi = -32768;
  for (uint8_t ci = 0; ci < nc; ci++) {
    uint16_t off = FONT_COFF[first + ci];
    uint16_t len = FONT_CLEN[first + ci];
    for (uint16_t i = 0; i < len; i++) {
      int16_t px = FONT_PTS[(off + i) * 2], py = FONT_PTS[(off + i) * 2 + 1];
      if (px < gxLo) gxLo = px;
      if (px > gxHi) gxHi = px;
      if (py < gyLo) gyLo = py;
      if (py > gyHi) gyHi = py;
    }
  }

  int xLo = (int)floorf(ox + gxLo * sx) - 1;
  int xHi = (int)ceilf (ox + gxHi * sx) + 1;
  int yLo = (int)floorf(oy + gyLo * sy) - 1;
  int yHi = (int)ceilf (oy + gyHi * sy) + 1;

  if (xLo < 0) xLo = 0;
  if (yLo < 0) yLo = 0;
  if (xHi > SW) xHi = SW;
  if (yHi > SH) yHi = SH;
  int w = xHi - xLo;
  if (w <= 0 || w > (int)(sizeof(cov)) ) return;

  const uint8_t step = 255 / SUBROWS;
  float xs[24];

  tft.startWrite();
  for (int y = yLo; y < yHi; y++) {
    memset(cov, 0, w);
    bool any = false;

    for (int s = 0; s < SUBROWS; s++) {
      float yc = y + (s + 0.5f) / SUBROWS;
      int   n  = 0;

      for (uint8_t ci = 0; ci < nc; ci++) {
        uint16_t off = FONT_COFF[first + ci];
        uint16_t len = FONT_CLEN[first + ci];
        for (uint16_t i = 0; i < len; i++) {
          uint16_t j = (i + 1 == len) ? 0 : i + 1;
          float ay = oy + FONT_PTS[(off + i) * 2 + 1] * sy;
          float by = oy + FONT_PTS[(off + j) * 2 + 1] * sy;
          if ((ay <= yc && by > yc) || (by <= yc && ay > yc)) {
            float ax = ox + FONT_PTS[(off + i) * 2] * sx;
            float bx = ox + FONT_PTS[(off + j) * 2] * sx;
            if (n < 24) xs[n++] = ax + (yc - ay) * (bx - ax) / (by - ay);
          }
        }
      }
      if (n < 2) continue;

      for (int a = 1; a < n; a++) {            // insertion sort
        float v = xs[a]; int b = a - 1;
        while (b >= 0 && xs[b] > v) { xs[b + 1] = xs[b]; b--; }
        xs[b + 1] = v;
      }

      for (int a = 0; a + 1 < n; a += 2) {
        float x1 = xs[a], x2 = xs[a + 1];
        if (x2 <= xLo || x1 >= xHi) continue;
        if (x1 < xLo) x1 = xLo;
        if (x2 > xHi) x2 = xHi;
        int p1 = (int)floorf(x1), p2 = (int)floorf(x2);
        any = true;
        if (p1 == p2) {
          int k = p1 - xLo;
          if (k >= 0 && k < w) cov[k] += (uint8_t)((x2 - x1) * step);
        } else {
          int k = p1 - xLo;
          if (k >= 0 && k < w) cov[k] += (uint8_t)((p1 + 1 - x1) * step);
          for (int p = p1 + 1; p < p2; p++) {
            k = p - xLo;
            if (k >= 0 && k < w) cov[k] += step;
          }
          k = p2 - xLo;
          if (k >= 0 && k < w) cov[k] += (uint8_t)((x2 - p2) * step);
        }
      }
    }

    if (!any) continue;
    for (int i = 0; i < w; i++) {
      uint16_t a = cov[i];
      if (a >= 250) rowBuf[i] = fg;
      else if (a == 0) rowBuf[i] = bg;
      else rowBuf[i] = blend565(fg, bg, a);
    }
    tft.setAddrWindow(xLo, y, w, 1);
    tft.writePixels(rowBuf, w);
  }
  tft.endWrite();
}

// Whole number, centered in the box, condensing rather than shrinking.
// Digit advances come from FONT_ADV; the TRACK gap is added on top.
void drawNumber(uint8_t n, int cx, int cy, int maxW, int maxH,
                uint16_t fg, uint16_t bg) {
  int gi[2];
  int digits;
  if (n >= 10) { gi[0] = fontIndex('0' + n / 10); gi[1] = fontIndex('0' + n % 10); digits = 2; }
  else         { gi[0] = fontIndex('0' + n);                                          digits = 1; }

  float gap    = TRACK * FONT_GRID;
  float totalW = (digits - 1) * gap;
  for (int i = 0; i < digits; i++) totalW += FONT_ADV[gi[i]];

  float sy = (float)maxH / FONT_GRID;
  float sx = fminf(sy, (float)maxW / totalW);
  if (sx < sy * CONDENSE) sy = sx / CONDENSE;

  float x = cx - (totalW * sx) * 0.5f;
  float y = cy - (FONT_GRID * sy) * 0.5f;

  for (int i = 0; i < digits; i++) {
    fillGlyph(gi[i], x, y, sx, sy, fg, bg);
    x += (FONT_ADV[gi[i]] + gap) * sx;
  }
}

// ---------------------------------------------------------------------------
void backlightInit() {
#if ESP_ARDUINO_VERSION_MAJOR >= 3
  ledcAttach(TFT_BL, 5000, 8);
#else
  ledcSetup(0, 5000, 8);
  ledcAttachPin(TFT_BL, 0);
#endif
}

void backlight(uint8_t duty) {
#if ESP_ARDUINO_VERSION_MAJOR >= 3
  ledcWrite(TFT_BL, duty);
#else
  ledcWrite(0, duty);
#endif
}

// ===========================================================================
// ESP-NOW link state
// ===========================================================================
static const uint8_t BCAST[6] = { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF };

uint8_t  myMac[6];
uint8_t  gatewayMac[6];
bool     gatewayKnown  = false;
int      myCupId       = -1;      // -1 until the gateway's hello-ack assigns one

DdmStatePacket lastState;
bool     haveState     = false;
uint32_t lastSeq       = 0;
bool     haveSeq       = false;
uint32_t droppedCount  = 0;       // gaps detected in the gateway's seq
int8_t   lastRssi      = 0;       // RSSI of the last gateway packet heard
uint32_t lastPacketAt  = 0;       // millis() of last gateway packet; 0 = never
uint32_t versionRejects = 0;

uint32_t tHello = 0, tTelemetry = 0;

// ---------------------------------------------------------------------------
// Scale state. Everything the HX711 produces lives here; the display never
// reads `tokens` except for the diagnostic overlay.
// ---------------------------------------------------------------------------
HX711 hx711;

enum ScalePhase : uint8_t {
  SCALE_WARMUP,    // first SCALE_WARMUP_MS after boot: sampling, not counting
  SCALE_TARING,    // collecting SCALE_TARE_SAMPLES for the empty reading
  SCALE_RUNNING    // counting
};

bool       scaleOk       = false;    // HX711 answered at boot
ScalePhase scalePhase    = SCALE_WARMUP;
uint32_t   tScaleWarmup  = 0;        // millis() at boot
uint32_t   tScaleSample  = 0;        // millis() of the last sample (baseline time constant)
long       tareSum       = 0;        // tare accumulator
uint8_t    tareN         = 0;
long       tare          = 0;        // raw counts that mean "empty"
long       lastReading   = 0;        // most recent raw sample
float      baseline      = 0;        // slow-tracking raw baseline the detector compares against
uint8_t    confirmN      = 0;        // consecutive samples past TOKEN_THRESHOLD
uint16_t   tokens        = 0;        // what telemetry reports as tokenCount
uint32_t   tLedOff       = 0;        // non-blocking end of the tare-acknowledge blink
long       countsPerToken = COUNTS_PER_TOKEN;  // per cup, NVS "cpt" (serial c<N>); the constant above until then
long       tokenThreshold = TOKEN_THRESHOLD;   // half of countsPerToken
uint32_t   tLastEvent    = 0;        // last drop/remove/tare: fast tracking and the settle check hang off it
bool       settlePending = false;    // an event happened; compare the settled load with the count once quiet
long       snapReading   = 0;        // reading the baseline snapped to at the last event (relaxation print)
long       ring[SETTLE_RING];        // the last ~2 s of samples, for the settle check
uint8_t    ringN         = 0;        // valid samples in ring (0 after every event)
uint8_t    ringI         = 0;
long       calNum        = 0;        // serial c<N>: digits being collected
int8_t     calDigits     = -1;       // -1 = not collecting
uint32_t   tCalDigit     = 0;        // last digit seen (the number ends 500 ms after it, any line ending)

// Handoff from the ESP-NOW receive callback (WiFi task) to loop(). The
// callback only copies bytes and sets a flag; all rendering and state
// mutation happens in loop().
volatile bool  rxStatePending = false;
volatile bool  rxAckPending   = false;
DdmStatePacket rxStateBuf;
uint8_t        rxAckCupId     = 0;
uint8_t        rxSrcMac[6];
int8_t         rxRssiVal      = 0;

// ---------------------------------------------------------------------------
// Receive path. Core 3.x hands us esp_now_recv_info_t (with per-packet RSSI);
// core 2.x hands us just the MAC. Same guard pattern as the LEDC handling.
// ---------------------------------------------------------------------------
#if ESP_ARDUINO_VERSION_MAJOR >= 3
void onDataRecv(const esp_now_recv_info_t* info, const uint8_t* data, int len) {
  const uint8_t* src = info->src_addr;
  int8_t rssi = info->rx_ctrl ? info->rx_ctrl->rssi : 0;
#else
void onDataRecv(const uint8_t* src, const uint8_t* data, int len) {
  int8_t rssi = 0;   // core 2.x recv path exposes no RSSI
#endif
  if (len < 2) return;
  if (data[0] != DDM_PROTO_VERSION) { versionRejects++; return; }

  if (data[1] == DDM_MSG_STATE && len == (int)sizeof(DdmStatePacket)) {
    memcpy(&rxStateBuf, data, sizeof(rxStateBuf));
    memcpy((void*)rxSrcMac, src, 6);
    rxRssiVal = rssi;
    rxStatePending = true;

  } else if (data[1] == DDM_MSG_HELLO && len == (int)sizeof(DdmTelemetryPacket)) {
    // Gateway's hello-ack: the DdmTelemetryPacket layout coming back at us
    // with cupId = the ID this cup was assigned (see gateway PROTOCOL NOTE).
    const DdmTelemetryPacket* p = (const DdmTelemetryPacket*)data;
    rxAckCupId = p->cupId;
    memcpy((void*)rxSrcMac, src, 6);
    rxRssiVal = rssi;
    rxAckPending = true;
  }
}

static void ensureGatewayPeer(const uint8_t* mac) {
  if (gatewayKnown && memcmp(gatewayMac, mac, 6) == 0) return;
  memcpy(gatewayMac, mac, 6);
  gatewayKnown = true;
  if (!esp_now_is_peer_exist(mac)) {
    esp_now_peer_info_t p = {};
    memcpy(p.peer_addr, mac, 6);
    p.channel = DDM_ESPNOW_CHANNEL;
    p.ifidx   = WIFI_IF_STA;
    p.encrypt = false;
    esp_now_add_peer(&p);
  }
  Serial.printf("[link] gateway %02X:%02X:%02X:%02X:%02X:%02X registered\n",
                mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
}

static void sendHello() {
  DdmTelemetryPacket p = {};
  p.version = DDM_PROTO_VERSION;
  p.msgType = DDM_MSG_HELLO;
  p.cupId   = (myCupId < 0) ? 0xFF : (uint8_t)myCupId;  // 0xFF = unassigned;
                                                        // gateway keys on MAC
  p.rssi    = lastRssi;
  esp_now_send(gatewayKnown ? gatewayMac : BCAST, (const uint8_t*)&p, sizeof(p));
}

static void sendTelemetry() {
  DdmTelemetryPacket p = {};
  p.version    = DDM_PROTO_VERSION;
  p.msgType    = DDM_MSG_TELEMETRY;
  p.cupId      = (uint8_t)myCupId;
  p.seq        = lastSeq;
  p.dropped    = droppedCount;
  p.rawWeight  = (int32_t)(lastReading - tare);   // net counts, uncalibrated
  p.tokenCount = tokens;
  p.rssi       = lastRssi;
  esp_now_send(gatewayMac, (const uint8_t*)&p, sizeof(p));
}

// ===========================================================================
// Rendering — redraw only when the rendered state actually changes.
// A full-screen glyph fill on every 500ms packet would flicker badly, so the
// current render inputs are compared against the last-rendered set and the
// draw is skipped when identical. Animated screens (scratched flash, podium
// cycle) keep their own timers.
// ===========================================================================
enum Screen : uint8_t {
  SCR_BOOT,        // nothing drawn yet
  SCR_WAITING,     // no cup ID yet: show own MAC big
  SCR_NO_HORSE,    // assigned, but horseForCup[me] == 0
  SCR_NUMBER,      // giant number on saddle cloth
  SCR_SCRATCHED,   // alternating flash
  SCR_PODIUM       // DDM_WINNER treatment
};

// NOTE: the Arduino .ino preprocessor hoists auto-generated prototypes above
// this struct, so functions below keep Rendered out of their signatures and
// work through the cur/lastDrawn globals instead.
struct Rendered {
  Screen  scr;
  uint8_t horse;
  bool    noLink;
};

Rendered cur         = { SCR_BOOT, 0, false };   // computed each render tick
Rendered lastDrawn   = { SCR_BOOT, 0, false };
bool     overlayOn   = false;
uint32_t tAnim       = 0;    // scratched/podium frame timer
uint8_t  animStep    = 0;
uint32_t tOverlay    = 0;

// --- screens ---------------------------------------------------------------

void drawWaiting() {
  tft.fillScreen(C_BLACK);
  textBg = C_BLACK;
  centerTextCap("LA QUINIELA", SW / 2, 30, SW - 24, C_AMBER, 30);
  centerTextCap("WAITING FOR", SW / 2, SH / 2 - 78, SW - 40, C_WHITE, 28);
  centerTextCap("GATEWAY",     SW / 2, SH / 2 - 46, SW - 40, C_WHITE, 28);

  // Own MAC, split across two lines and allowed a taller cap than the rest
  // so it can be read and typed into KNOWN_CUPS[] without a serial cable.
  char l1[12], l2[12];
  snprintf(l1, sizeof(l1), "%02X:%02X:%02X", myMac[0], myMac[1], myMac[2]);
  snprintf(l2, sizeof(l2), "%02X:%02X:%02X", myMac[3], myMac[4], myMac[5]);
  centerTextCap(l1, SW / 2, SH / 2 + 16, SW - 16, C_GOLD, 40);
  centerTextCap(l2, SW / 2, SH / 2 + 66, SW - 16, C_GOLD, 40);

  centerTextCap("MAC ADDRESS", SW / 2, SH - 28, SW - 24, C_DIM, 16);

  // Scale note, only while the HX711 is still warming up or taring, so it is
  // obvious why nothing is being counted yet. Small Impact, in the free band
  // between the MAC and its caption.
  if (scaleOk && scalePhase != SCALE_RUNNING)
    drawText("SCALE WARMING UP", SW / 2, SH - 66, 14, C_AMBER, C_BLACK);
}

void drawNoHorse() {
  tft.fillScreen(C_BLACK);
  textBg = C_BLACK;
  char buf[16];
  snprintf(buf, sizeof(buf), "CUP %d", myCupId);
  centerText(buf, SW / 2, SH / 2 - 24, SW - 30, C_WHITE);
  centerText("NO HORSE", SW / 2, SH / 2 + 24, SW - 30, C_DIM);
}

void drawGiant(uint8_t n) {
  Cloth c = cloth(n);
  tft.fillScreen(c.bg);
  drawNumber(n, SW / 2, SH / 2, SW - 16, SH - 36, c.fg, c.bg);
}

// Scratched frame A: greyed number with SCRATCHED (geometry from the
// prototype's scratched screen, minus the X)
void drawScratchedNumber(uint8_t n) {
  tft.fillScreen(C_BLACK);
  textBg = C_BLACK;

  int foot = 52;
  int side = min(SW - 30, SH - foot - 36);
  int cx   = SW / 2;
  int cy   = (SH - foot) / 2;

  drawNumber(n, cx, cy, side, side, C_DIM, C_BLACK);
  centerText("SCRATCHED", cx, SH - foot / 2, SW - 20, C_RED);
}

// Scratched frame B: the boxed X (X stroke thickness from the prototype)
void drawScratchedX() {
  tft.fillScreen(C_BLACK);

  int side = min(SW, SH) - 70;
  int cx   = SW / 2;
  int cy   = SH / 2;
  int h    = side / 2;

  tft.drawRect(cx - h - 14, cy - h - 14, side + 28, side + 28, C_RED);
  tft.drawRect(cx - h - 15, cy - h - 15, side + 30, side + 30, C_RED);

  int t = max(5, side / 26);
  for (int i = -t / 2; i <= t / 2; i++) {
    tft.drawLine(cx - h + i, cy - h, cx + h + i, cy + h, C_RED);
    tft.drawLine(cx + h + i, cy - h, cx - h + i, cy + h, C_RED);
  }
}

// Podium treatment from the prototype, applied to this cup's own horse.
// PROTOCOL NOTE: DdmStatePacket carries no win/place/show results, so in
// DDM_WINNER every cup cycles the metal treatment on its own number.
void drawPodiumFrame(uint8_t step, uint8_t horse) {
  const char* labels[3] = { "WIN", "PLACE", "SHOW" };
  uint16_t    metals[3] = { C_GOLD, C_SILVER, C_BRONZE };
  uint8_t     i = step % 3;

  tft.fillScreen(C_BLACK);
  textBg = C_BLACK;
  tft.drawRect(6, 6, SW - 12, SH - 12, metals[i]);
  tft.drawRect(7, 7, SW - 14, SH - 14, metals[i]);

  int foot = 56;
  drawNumber(horse, SW / 2, (SH - foot) / 2,
             SW - 40, SH - foot - 40, metals[i], C_BLACK);

  // 4 px higher and capped at 28 so the label's anti-aliased box never
  // paints over the frame lines just below it.
  centerTextCap(labels[i], SW / 2, SH - foot / 2 - 4, SW - 30, metals[i], 28);
}

// --- badges / overlay ------------------------------------------------------

void drawNoLinkBadge() {
  tft.fillRect(0, 0, 88, 20, C_BLACK);
  tft.drawRect(0, 0, 88, 20, C_RED);
  drawText("NO LINK", 44, 5, 11, C_RED, C_BLACK);
}

void drawOverlay() {
  uint32_t now = millis();
  int h = 78;                       // four lines of 11 px Impact
  int y = SH - h;
  uint8_t horse = 0, st = 0;
  if (haveState && myCupId >= 0) {
    horse = lastState.horseForCup[myCupId];
    st    = lastState.raceState;
  }

  tft.fillRect(0, y, SW, h, C_BLACK);
  tft.drawRect(0, y, SW, h, C_AMBER);

  // Uppercase only, and no '+': the glyph set has 0-9 A-Z space % : - . ! ? /
  const int cap = 11, pitch = 17, x0 = 6;
  char line[48];
  snprintf(line, sizeof(line), "ID:%d  HORSE:%u  STATE:%u  VER!:%lu",
           myCupId, horse, st, (unsigned long)versionRejects);
  drawTextLeft(line, x0, y + 5, cap, C_WHITE, C_BLACK);

  snprintf(line, sizeof(line), "RSSI:%d DBM  DROP:%lu", lastRssi, (unsigned long)droppedCount);
  drawTextLeft(line, x0, y + 5 + pitch, cap, C_WHITE, C_BLACK);

  if (lastPacketAt == 0)
    snprintf(line, sizeof(line), "SEQ:-  AGE:NEVER");
  else
    snprintf(line, sizeof(line), "SEQ:%lu  AGE:%luMS",
             (unsigned long)lastSeq, (unsigned long)(now - lastPacketAt));
  drawTextLeft(line, x0, y + 5 + 2 * pitch, cap, C_WHITE, C_BLACK);

  if (!scaleOk)
    snprintf(line, sizeof(line), "TOKENS:-  NET:-  NO HX711");
  else
    snprintf(line, sizeof(line), "TOKENS:%u  NET:%ld  %s", tokens, lastReading - tare,
             scalePhase == SCALE_WARMUP ? "WARMUP" :
             scalePhase == SCALE_TARING ? "TARING" : "OK");
  drawTextLeft(line, x0, y + 5 + 3 * pitch, cap, C_WHITE, C_BLACK);
}

// --- render decision --------------------------------------------------------

static void computeRendered() {   // fills `cur`
  cur.noLink = (lastPacketAt != 0) && (millis() - lastPacketAt > LINK_TIMEOUT_MS);

  if (myCupId < 0) {
    cur.scr = SCR_WAITING; cur.horse = 0;
    return;
  }

  uint8_t horse     = haveState ? lastState.horseForCup[myCupId] : 0;
  uint8_t scratched = haveState ? lastState.scratched[myCupId]   : 0;
  uint8_t state     = haveState ? lastState.raceState            : DDM_PRE_RACE;

  if (horse == 0)                { cur.scr = SCR_NO_HORSE;  cur.horse = 0;     }
  else if (scratched)            { cur.scr = SCR_SCRATCHED; cur.horse = horse; }
  else if (state == DDM_WINNER)  { cur.scr = SCR_PODIUM;    cur.horse = horse; }
  else                           { cur.scr = SCR_NUMBER;    cur.horse = horse; }
}

static void drawBase() {          // draws `cur`
  const Rendered& r = cur;
  switch (r.scr) {
    case SCR_WAITING:   drawWaiting();                    break;
    case SCR_NO_HORSE:  drawNoHorse();                    break;
    case SCR_NUMBER:    drawGiant(r.horse);               break;
    case SCR_SCRATCHED: animStep = 0; tAnim = millis();
                        drawScratchedNumber(r.horse);     break;
    case SCR_PODIUM:    animStep = 0; tAnim = millis();
                        drawPodiumFrame(0, r.horse);      break;
    default: break;
  }
  if (r.noLink && r.scr != SCR_WAITING) drawNoLinkBadge();
  if (overlayOn) drawOverlay();
}

static void renderTick() {
  uint32_t now = millis();
  computeRendered();
  const Rendered& r = cur;

  // Full redraw only when something actually changed
  if (r.scr != lastDrawn.scr || r.horse != lastDrawn.horse ||
      r.noLink != lastDrawn.noLink) {
    drawBase();
    lastDrawn = r;
    return;
  }

  // Animated screens advance on their own timers
  if (r.scr == SCR_SCRATCHED && now - tAnim >= SCRATCH_FLASH_MS) {
    tAnim = now;
    animStep++;
    if (animStep & 1) drawScratchedX();
    else              drawScratchedNumber(r.horse);
    if (r.noLink) drawNoLinkBadge();
    if (overlayOn) drawOverlay();
  } else if (r.scr == SCR_PODIUM && now - tAnim >= PODIUM_STEP_MS) {
    tAnim = now;
    drawPodiumFrame(++animStep, r.horse);
    if (r.noLink) drawNoLinkBadge();
    if (overlayOn) drawOverlay();
  }

  // Overlay values refresh while visible
  if (overlayOn && now - tOverlay >= OVERLAY_MS) {
    tOverlay = now;
    drawOverlay();
  }
}

// ---------------------------------------------------------------------------
// The CYD's display controller is not an ILI9341: the panel probe
// (tools/panel_probe) reads an ST7789-family register map on every board.
// Two things in the Adafruit ILI9341 init table go wrong on it:
//
//  * It sends a Vertical Scrolling Start Address (0x37) and never Normal
//    Display Mode ON, which leaves the panel in vertical-scroll mode (status
//    register bit D15 reads 1 after tft.begin()). On these panels the bottom
//    quarter of the glass then stops following frame memory: writes land,
//    nothing shows. Define the scroll area as the whole panel, zero the
//    scroll start and send NORON (0x13).
//
//  * It writes 0xC0 = 0x23. On an ILI9341 that is Power Control 1; on an
//    ST7789 it is LCMCTRL, a byte of XOR flags laid over MADCTL:
//    0x23 = XBGR | XMV | XGS. XMV inverts the meaning of MADCTL's MV
//    (row/column exchange) bit. While the panel is scrolling MV is not
//    applied, which is why rotation 0 looked right before the NORON fix and
//    rotations 1/3 "stayed portrait"; the moment scroll mode ends the
//    inverted MV bit takes effect and rotation 0 comes out transposed.
//    XBGR likewise inverts the driver's BGR bit, so the glass ran in RGB
//    order and horse 1's red cloth came up blue (Board A, 2026-09-12).
//    Rewrite LCMCTRL with XMV and XBGR cleared, keeping only XGS as the
//    init left it (0x01); panelOrientation() picks the MADCTL that is
//    upright with XGS set.
//
// The scroll commands go to every board (the band was on every board). The
// 0xC0 write only goes to boards with a non-zero RDDID: on an ILI9341 that
// register is Power Control 1 and 0x01 would be an out-of-range GVDD, and
// the zero-ID batch (RDDID and RDID4 both 00 00 00, textbook status bits,
// upright with the library's own 0x48) looks like an ILI9341.
// ---------------------------------------------------------------------------
static void panelNormalMode() {
  static const uint8_t lcmctrl[1] = { 0x01 };                               // XGS only: XMV and XBGR cleared
  static const uint8_t vscrdef[6] = { 0x00, 0x00, 0x01, 0x40, 0x00, 0x00 }; // TFA 0, VSA 320, BFA 0
  static const uint8_t vscsad[2]  = { 0x00, 0x00 };                         // scroll start 0
  if (panelIsSt7789Family()) {
    tft.sendCommand(0xC0, lcmctrl, 1);                                      // LCMCTRL: MV means MV, BGR means BGR
    Serial.println("panel: ST7789-family ID, LCMCTRL rewritten");
  } else {
    Serial.println("panel: zero ID (ILI9341-like), LCMCTRL left alone");   // 0xC0 is Power Control 1 there
  }
  tft.sendCommand(0x33, vscrdef, 6);
  tft.sendCommand(0x37, vscsad, 2);
  tft.sendCommand(0x13);                                                    // NORON: scroll mode off
}

// ---------------------------------------------------------------------------
// The driver's portrait MADCTL values assume an ILI9341 glass: 0x48 (MX|BGR)
// for rotation 0 and 0x88 (MY|BGR) for rotation 2. On these panels, once
// they are out of scroll mode, 0x48 comes out flipped top-to-bottom and
// 0x88 flipped left-to-right (Board A, 2026-09-12). Upright needs MX and MY
// both set, which no library rotation produces, so setRotation() is used
// for its width/height bookkeeping only and the MADCTL byte is sent here.
// BGR stays set as the driver would send it; colour order is LCMCTRL's job.
// The cup with the scale (2026-09-15) wants MX alone (0x48): same build,
// vertical flip the other way, so the glass is wired differently between
// board batches. Which MX/MY pair is upright is therefore a per-cup setting:
// the default comes from the panel's RDDID bytes (panelDefaultFlips), NVS
// holds the real bits, and serial o/h/v or a 15 s BOOT hold change and save them.
// ---------------------------------------------------------------------------
static void panelOrientation() {
  uint8_t madctl = 0x08 | orientFlips;                  // BGR | MX? | MY?
  tft.sendCommand(0x36, &madctl, 1);                    // MADCTL
}

static void panelSetOrientation(uint8_t flips, const char* how) {
  orientFlips = flips & 0xC0;
  prefs.putUChar("flip", orientFlips);
  panelOrientation();
  lastDrawn.scr = SCR_BOOT;                             // full redraw on the next tick
  Serial.printf("[panel] orientation MADCTL 0x%02X saved to NVS (%s)\n", 0x08 | orientFlips, how);
}

// Next of the four settings, one bit at a time: C8 -> 48 -> 08 -> 88 -> C8.
static void panelNextOrientation(const char* how) {
  static const uint8_t cycle[4] = { 0xC0, 0x40, 0x00, 0x80 };
  uint8_t i = 0;
  while (i < 3 && cycle[i] != orientFlips) i++;
  panelSetOrientation(cycle[(i + 1) & 3], how);
}

// ---------------------------------------------------------------------------
// Panel identity, read raw over SPI at 2 MHz with the one-bit realignment for
// the dummy clock, exactly as tools/panel_probe does it.
//   Board A (ST7789-family clone): RDDID 10 81 B3 after tft.begin(), RDID4 FF FF FF
//   The cup with the scale, 2026-09-15:  RDDID 00 00 00 (what a genuine ILI9341
//   answers too; RDID4 and RDDST are logged to tell the two apart)
// The RDDID bytes pick the orientation default for a cup with nothing in NVS.
// ---------------------------------------------------------------------------
uint8_t panelRddid[3] = { 0, 0, 0 };
uint8_t panelRdid4[3] = { 0, 0, 0 };

static void panelRawRead(uint8_t cmd, uint8_t* buf, uint8_t n) {
  SPI.beginTransaction(SPISettings(2000000, MSBFIRST, SPI_MODE0));
  digitalWrite(TFT_CS, LOW);
  digitalWrite(TFT_DC, LOW);
  SPI.transfer(cmd);
  digitalWrite(TFT_DC, HIGH);
  for (uint8_t i = 0; i < n; i++) buf[i] = SPI.transfer(0x00);
  digitalWrite(TFT_CS, HIGH);
  SPI.endTransaction();
}

static void panelRead3(uint8_t cmd, uint8_t* out, uint8_t* raw) {   // 3 bytes after one dummy clock
  panelRawRead(cmd, raw, 4);
  for (uint8_t i = 0; i < 3; i++) out[i] = (uint8_t)((raw[i] << 1) | (raw[i + 1] >> 7));
}

static uint32_t panelReadStatus() {                                 // RDDST, 32 bits after one dummy clock
  uint8_t in[5];
  panelRawRead(0x09, in, 5);
  uint32_t st = 0;
  for (uint8_t i = 0; i < 4; i++) st = (st << 8) | (uint8_t)((in[i] << 1) | (in[i + 1] >> 7));
  return st;
}

static void panelLogStatus(const char* when) {
  uint32_t st = panelReadStatus();
  Serial.printf("panel RDDST %s: 0x%08lX  scroll %s  normal %s  MADCTL MY%u MX%u MV%u\n",
                when, (unsigned long)st,
                (st & (1UL << 15)) ? "ON" : "off", (st & (1UL << 16)) ? "on" : "OFF",
                (unsigned)((st >> 30) & 1), (unsigned)((st >> 29) & 1), (unsigned)((st >> 28) & 1));
}

static void panelLogIds() {
  uint8_t raw1[4], raw2[4];
  panelRead3(0x04, panelRddid, raw1);
  panelRead3(0xD3, panelRdid4, raw2);
  Serial.printf("panel RDDID: %02X %02X %02X (raw %02X %02X %02X %02X)   RDID4: %02X %02X %02X (raw %02X %02X %02X %02X)   Board A: 10 81 B3 / FF FF FF\n",
                panelRddid[0], panelRddid[1], panelRddid[2], raw1[0], raw1[1], raw1[2], raw1[3],
                panelRdid4[0], panelRdid4[1], panelRdid4[2], raw2[0], raw2[1], raw2[2], raw2[3]);
}

static bool panelIsSt7789Family() {                    // non-zero RDDID: Board A's 10 81 B3, or a real ST7789V's 85 85 52
  return (panelRddid[0] | panelRddid[1] | panelRddid[2]) != 0;
}

static uint8_t panelDefaultFlips() {
  return panelIsSt7789Family() ? ORIENT_DEFAULT : ORIENT_DEFAULT_ID00;
}

static void panelUseDefaultOrientation() {                          // serial 'x': NVS forgotten
  orientFlips = panelDefaultFlips();
  panelOrientation();
  lastDrawn.scr = SCR_BOOT;
  Serial.printf("[panel] orientation MADCTL 0x%02X = default for RDDID %02X %02X %02X (saved setting cleared)\n",
                0x08 | orientFlips, panelRddid[0], panelRddid[1], panelRddid[2]);
}

// ===========================================================================
// SCALE — HX711 token counting
//
// Counting is by increments against a slow-tracking baseline, never by an
// unsettled weight: a stack of tokens keeps relaxing for 10-15 s after every
// impact (about 2% of the total load), so a raw weight is roughly a token in
// sixty off while that lasts. The baseline is a low-pass of the reading
// (time constant SCALE_BASELINE_TAU_MS, SCALE_FAST_TAU_MS while a stack is
// relaxing) that only updates while the reading is within half a token of
// it, so warm-up drift and post-impact relaxation are absorbed and never
// counted. A jump of at least half a token that holds for
// SCALE_CONFIRM_SAMPLES consecutive samples is an event: the step is rounded
// to whole tokens (two dropped together count as two), the baseline snaps to
// the new reading, and tracking resumes. Downward steps decrement the same
// way. A bump spikes and returns within a sample or two, so it never confirms.
//
// Two corrections keep a big stack honest (bench, 2026-09-15: 50 tokens
// counted as 51..58 without them):
//  * The impact overshoot scales with the load already on the plate, so a
//    drop onto forty tokens measures about 1.8 tokens. OVERSHOOT_PCT of that
//    load is taken off the step before rounding, with a floor of one token
//    so a gently placed token still counts.
//  * SCALE_POST_EVENT_MS after the last event, once the reading has been
//    flat for SETTLE_RING samples, the settled load is compared with the
//    count and the count is corrected by at most SETTLE_MAX_FIX tokens; a
//    bigger disagreement is reported and left for serial 's', because on the
//    bench the same 50 tokens settled at 50.6, 53.2 and 51.5 tokens as the
//    cup was shaken (2026-09-15): a mechanical hysteresis no software can
//    remove. Only a settled reading is ever used for that. A load within
//    SETTLE_AMBIGUOUS of a half token is left alone and reported, so a
//    mis-calibrated cup cannot flip-flop.
// Serial c<N> calibrates the cup from N settled tokens and stores the result
// in NVS: load cells differ by several percent from unit to unit.
//
// Everything here is non-blocking: the ADC is only read when is_ready() says
// a conversion is waiting, so the display and the radio never stall on it.
// ===========================================================================
static void scaleStartTare(const char* why, bool blink) {
  scalePhase = SCALE_TARING;
  tareSum    = 0;
  tareN      = 0;
  confirmN   = 0;
  tokens     = 0;                       // a tare means "this is empty"
  settlePending = false;
  ringN = 0; ringI = 0;
  Serial.printf("[tare] %s: averaging %d samples\n", why, SCALE_TARE_SAMPLES);
  if (blink) {
    digitalWrite(LED_G, LOW);           // CYD LEDs are active low
    tLedOff = millis() + TARE_BLINK_MS;
  }
}

static void scaleSetCpt(long cpt, const char* how) {
  if (cpt < 1000 || cpt > 200000) {
    Serial.printf("[cal] %ld counts/token rejected (%s)\n", cpt, how);
    return;
  }
  countsPerToken = cpt;
  tokenThreshold = cpt / 2;
  Serial.printf("[cal] %ld counts/token (%s), threshold %ld\n", countsPerToken, how, tokenThreshold);
}

// Flat enough to trust: max-min over the ring under SETTLE_SPREAD. Fills
// *mean with the ring average.
static bool scaleSettled(long* mean) {
  if (ringN < SETTLE_RING) return false;
  long mn = ring[0], mx = ring[0]; long long sum = 0;
  for (uint8_t i = 0; i < SETTLE_RING; i++) {
    if (ring[i] < mn) mn = ring[i];
    if (ring[i] > mx) mx = ring[i];
    sum += ring[i];
  }
  *mean = (long)(sum / SETTLE_RING);
  return (mx - mn) <= SETTLE_SPREAD;
}

// Serial c<N>: N tokens are on the plate and the cup is quiet. c0 forgets the
// stored calibration.
static void scaleCalibrate(long n) {
  if (n == 0) {
    prefs.remove("cpt");
    scaleSetCpt(COUNTS_PER_TOKEN, "c0: back to the default");
    return;
  }
  if (scalePhase != SCALE_RUNNING) { Serial.println("[cal] scale not running yet"); return; }
  if (n < 1 || n > 1000) { Serial.printf("[cal] c%ld: give the number of tokens on the plate, 1..1000\n", n); return; }
  long settled;
  if (!scaleSettled(&settled)) {
    Serial.println("[cal] not settled: wait 15-20 s after the last drop, hands off, then try again");
    return;
  }
  long load = settled - tare;
  if (load < n * 100) { Serial.printf("[cal] load %ld counts is too small for %ld tokens\n", load, n); return; }
  long cpt = load / n;
  scaleSetCpt(cpt, "c<N>");
  if (countsPerToken != cpt) return;                      // rejected
  prefs.putLong("cpt", cpt);
  tokens        = (uint16_t)n;
  baseline      = (float)settled;
  settlePending = false;
  Serial.printf("[cal] saved to NVS; tokens set to %ld\n", n);
}

// Once the cup has been quiet long enough after an event, trust the settled
// load over the running count.
static void scaleSettleCheck(uint32_t now) {
  if (!settlePending || now - tLastEvent < SCALE_POST_EVENT_MS) return;
  long settled;
  if (!scaleSettled(&settled)) return;                    // still relaxing, or someone is touching it
  long  load = settled - tare;
  float ft   = (float)load / (float)countsPerToken;
  long  nS   = lroundf(ft);
  if (nS < 0) nS = 0;
  long  relaxed = snapReading - settled;
  float relPct  = (settled - tare) > 0 ? 100.0f * (float)relaxed / (float)(settled - tare) : 0.0f;
  settlePending = false;
  baseline      = (float)settled;
  if (fabsf(ft - (float)nS) > SETTLE_AMBIGUOUS) {
    Serial.printf("[settle] ambiguous: load %ld = %.2f tokens, count stays %u (relaxed %ld = %.1f%% of load since the last drop)\n",
                  load, ft, tokens, relaxed, relPct);
    return;
  }
  if (nS != tokens) {
    long dif = nS - (long)tokens;
    if (labs(dif) > SETTLE_MAX_FIX) {
      Serial.printf("[settle] DISAGREES by %+ld: count %u, load %ld = %.2f tokens, not applied (SETTLE_MAX_FIX %d; serial s applies it) (relaxed %ld = %.1f%% of load since the last drop)\n",
                    dif, tokens, load, ft, SETTLE_MAX_FIX, relaxed, relPct);
      return;
    }
    Serial.printf("[settle] tokens %u -> %ld: load %ld = %.2f tokens (relaxed %ld = %.1f%% of load since the last drop)\n",
                  tokens, nS, load, ft, relaxed, relPct);
    tokens = (uint16_t)nS;
  } else {
    Serial.printf("[settle] ok tokens=%u: load %ld = %.2f tokens (relaxed %ld = %.1f%% of load since the last drop)\n",
                  tokens, load, ft, relaxed, relPct);
  }
}

// Serial 's': the operator knows the cup is right, take the settled load as
// the count regardless of SETTLE_MAX_FIX.
static void scaleApplySettled() {
  if (scalePhase != SCALE_RUNNING) { Serial.println("[settle] scale not running yet"); return; }
  long settled;
  if (!scaleSettled(&settled)) { Serial.println("[settle] not settled right now: hands off, wait a few seconds, try again"); return; }
  long  load = settled - tare;
  float ft   = (float)load / (float)countsPerToken;
  long  nS   = lroundf(ft);
  if (nS < 0) nS = 0;
  Serial.printf("[settle] serial s: tokens %u -> %ld (load %ld = %.2f tokens)\n", tokens, nS, load, ft);
  tokens        = (uint16_t)nS;
  baseline      = (float)settled;
  settlePending = false;
}

static void scaleTick(uint32_t now) {
  if (tLedOff && (int32_t)(now - tLedOff) >= 0) {
    digitalWrite(LED_G, HIGH);
    tLedOff = 0;
  }
  if (!scaleOk) return;

  if (scalePhase == SCALE_WARMUP && now - tScaleWarmup >= SCALE_WARMUP_MS)
    scaleStartTare("warm-up done", false);

  if (!hx711.is_ready()) return;        // nothing waiting: never block on the ADC
  long r = hx711.read();
  uint32_t dt = now - tScaleSample;
  tScaleSample = now;
  lastReading  = r;

  switch (scalePhase) {
    case SCALE_WARMUP:
      return;                           // sampling only, so the overlay has a live number

    case SCALE_TARING:
      tareSum += r;
      if (++tareN >= SCALE_TARE_SAMPLES) {
        tare       = tareSum / SCALE_TARE_SAMPLES;
        baseline   = (float)tare;
        scalePhase = SCALE_RUNNING;
        tLastEvent = now;
        Serial.printf("[tare] offset=%ld tokens=%u\n", tare, tokens);
        if (cur.scr == SCR_WAITING) lastDrawn.scr = SCR_BOOT;   // drop the WARMING UP note
      }
      return;

    case SCALE_RUNNING: {
      ring[ringI] = r;
      ringI = (uint8_t)((ringI + 1) % SETTLE_RING);
      if (ringN < SETTLE_RING) ringN++;

      float delta = (float)r - baseline;
      if (fabsf(delta) < (float)tokenThreshold) {
        // Quiet: track slowly, faster while the stack is still relaxing after an
        // event. alpha = dt / tau, capped so a long gap cannot overshoot.
        confirmN = 0;
        uint32_t tau = (now - tLastEvent < SCALE_POST_EVENT_MS) ? SCALE_FAST_TAU_MS : SCALE_BASELINE_TAU_MS;
        float a = (float)dt / (float)tau;
        if (a > 1.0f) a = 1.0f;
        baseline += delta * a;
        if (tokens == 0) tare = lroundf(baseline);   // an empty cup keeps re-zeroing itself
        scaleSettleCheck(now);
        return;
      }
      if (++confirmN < SCALE_CONFIRM_SAMPLES) return;   // a bump does not get this far
      confirmN = 0;

      float est  = delta / (float)countsPerToken;       // raw step in tokens
      float comp = est;
      long  n;
      if (delta > 0) {
        float load = baseline - (float)tare;              // what was already on the plate
        if (load < 0) load = 0;
        comp = (delta - load * (OVERSHOOT_PCT / 100.0f)) / (float)countsPerToken;
        n = lroundf(comp);
        if (n < 1 && lroundf(est) >= 1) n = 1;           // a real drop never rounds away
      } else {
        n = lroundf(est);
      }
      if (n > 0) {
        tokens += (uint16_t)n;
        Serial.printf("[drop] +%ld tokens=%u step=%ld baseline=%ld est=%.2f comp=%.2f\n",
                      n, tokens, (long)delta, (long)baseline, est, comp);
      } else if (n < 0) {
        long take = -n;
        if (take > tokens) take = tokens;                 // clamp at 0
        tokens -= (uint16_t)take;
        Serial.printf("[remove] -%ld tokens=%u step=%ld baseline=%ld\n",
                      take, tokens, (long)delta, (long)baseline);
      }
      baseline      = (float)r;                           // snap, then resume tracking
      snapReading   = r;
      tLastEvent    = now;
      settlePending = true;
      ringN = 0; ringI = 0;
      return;
    }
  }
}

// ===========================================================================
void setup() {
  Serial.begin(115200);
  delay(300);
  Serial.println();
  Serial.println("DDM La Quiniela cup — ESP-NOW bench test");

  pinMode(LED_R, OUTPUT); digitalWrite(LED_R, HIGH);
  pinMode(LED_G, OUTPUT); digitalWrite(LED_G, HIGH);
  pinMode(LED_B, OUTPUT); digitalWrite(LED_B, HIGH);
  pinMode(BOOT_BTN, INPUT_PULLUP);

  SPI.begin(TFT_SCLK, TFT_MISO, TFT_MOSI, TFT_CS);

  // Per-cup settings from NVS (survive reflashing; only an NVS erase clears them)
  prefs.begin("ddmcup", false);
  if (prefs.isKey("rot")) prefs.remove("rot");          // key from the two-way version of this setting
  bool haveFlip = prefs.isKey("flip");
  orientFlips = prefs.getUChar("flip", ORIENT_DEFAULT) & 0xC0;

  tft.begin();
  panelLogIds();
  panelLogStatus("after tft.begin()");
  if (!haveFlip) orientFlips = panelDefaultFlips();      // nothing saved: default by panel batch
  panelNormalMode();
  panelLogStatus("after panelNormalMode()");
  tft.setRotation(0);          // library bookkeeping only: 240 wide, 320 tall
  panelOrientation();          // the MADCTL this cup is set to
  Serial.printf("orientation MADCTL 0x%02X %s; serial o/h/v/x or BOOT held 15 s changes it\n",
                0x08 | orientFlips, haveFlip ? "from NVS" : "= default for this panel ID");
  tft.invertDisplay(INVERT);

  SW = tft.width();
  SH = tft.height();
  Serial.printf("screen %dx%d\n", SW, SH);

  backlightInit();
  backlight(255);

  // ESP-NOW only: STA mode, never associated, pinned channel
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(100);
  esp_wifi_set_channel(DDM_ESPNOW_CHANNEL, WIFI_SECOND_CHAN_NONE);

  WiFi.macAddress(myMac);
  Serial.printf("cup MAC: %02X:%02X:%02X:%02X:%02X:%02X  proto v%d  channel %d\n",
                myMac[0], myMac[1], myMac[2], myMac[3], myMac[4], myMac[5],
                DDM_PROTO_VERSION, DDM_ESPNOW_CHANNEL);

  if (esp_now_init() != ESP_OK) {
    Serial.println("FATAL esp_now_init failed");
    tft.fillScreen(C_BLACK);
    textBg = C_BLACK;
    centerText("ESP-NOW FAIL", SW / 2, SH / 2, SW - 20, C_RED);
    while (true) delay(1000);
  }
  esp_now_register_recv_cb(onDataRecv);

  // Broadcast peer for the hello phase, before the gateway MAC is known
  esp_now_peer_info_t p = {};
  memcpy(p.peer_addr, BCAST, 6);
  p.channel = DDM_ESPNOW_CHANNEL;
  p.ifidx   = WIFI_IF_STA;
  p.encrypt = false;
  esp_now_add_peer(&p);

  // Scale. The only blocking call is this one-second boot check; if the
  // HX711 is missing the cup runs without counting and the overlay says so.
  hx711.begin(HX711_DT, HX711_SCK, 128);
  pinMode(HX711_DT, INPUT_PULLUP);      // a missing amplifier reads "not ready", not garbage
  scaleOk      = hx711.wait_ready_timeout(1000, 10);
  tScaleWarmup = millis();
  tScaleSample = tScaleWarmup;
  Serial.printf("scale: %s\n", scaleOk
                ? "HX711 ok, warming up 30 s before tare"
                : "no HX711 on CN1 (DT 27, SCK 22), counting disabled");
  countsPerToken = prefs.getLong("cpt", COUNTS_PER_TOKEN);
  if (countsPerToken < 1000 || countsPerToken > 200000) countsPerToken = COUNTS_PER_TOKEN;
  tokenThreshold = countsPerToken / 2;
  Serial.printf("scale: %ld counts/token%s, threshold %ld; serial c<N> recalibrates with N tokens on the plate\n",
                countsPerToken, prefs.isKey("cpt") ? " from NVS" : " (default)", tokenThreshold);

  renderTick();   // puts up the waiting screen
}

void loop() {
  uint32_t now = millis();

  // --- BOOT button: short press toggles the diagnostic overlay; held for
  //     TARE_HOLD_MS it re-tares the scale, kept held to ORIENT_HOLD_MS it
  //     steps the display orientation and saves it (neither press toggles)
  static bool     down      = false;
  static uint32_t downAt    = 0;
  static uint8_t  holdStage = 0;      // 0 nothing yet, 1 tare fired, 2 flip fired

  bool pressed = (digitalRead(BOOT_BTN) == LOW);
  if (pressed && !down) {
    down = true; downAt = now; holdStage = 0;
  } else if (pressed && down && holdStage == 0 && now - downAt >= TARE_HOLD_MS) {
    holdStage = 1;                    // fires once per hold, while still held
    if (scaleOk) scaleStartTare("BOOT held", true);
    else         Serial.println("[tare] ignored: no HX711");
  } else if (pressed && down && holdStage == 1 && now - downAt >= ORIENT_HOLD_MS) {
    holdStage = 2;
    panelNextOrientation("BOOT held");
  } else if (!pressed && down) {
    down = false;
    if (holdStage == 0 && now - downAt > 30) {   // debounce; a hold is not a short press
      overlayOn = !overlayOn;
      Serial.printf("[btn] overlay %s\n", overlayOn ? "on" : "off");
      if (overlayOn) { tOverlay = now; drawOverlay(); }
      else           { lastDrawn.scr = SCR_BOOT; }   // force base redraw
    }
  }

  // --- serial commands (bench): o/h/v/x orientation, t = tare, c<N> = calibrate
  while (Serial.available()) {
    char c = (char)Serial.read();
    if (calDigits >= 0 && c >= '0' && c <= '9') {         // digits after a 'c'
      calNum = calNum * 10 + (c - '0');
      calDigits++;
      tCalDigit = now;
      continue;
    }
    if (calDigits > 0) {                                  // anything else ends the number
      scaleCalibrate(calNum);
      calDigits = -1;
    }
    if      (c == 'c') { calNum = 0; calDigits = 0; tCalDigit = now; }
    else if (c == 'o') panelNextOrientation("serial o");
    else if (c == 'h') panelSetOrientation(orientFlips ^ 0x40, "serial h: mirror left-right");
    else if (c == 'v') panelSetOrientation(orientFlips ^ 0x80, "serial v: mirror top-bottom");
    else if (c == 'x') { prefs.remove("flip"); panelUseDefaultOrientation(); }
    else if (c == 't') { if (scaleOk) scaleStartTare("serial", true); else Serial.println("[tare] ignored: no HX711"); }
    else if (c == 's') scaleApplySettled();
    else if (c == '?') Serial.println("commands: o = next orientation, h = mirror left-right, v = mirror top-bottom (all saved to NVS), "
                                      "x = forget the saved orientation and use the panel-ID default, t = tare, s = apply the settled load to the count, "
                                      "c<N> = N tokens are on the plate, calibrate counts/token and save (c0 forgets it), ? = help");
  }
  if (calDigits > 0 && now - tCalDigit > 500) {            // no line ending needed
    scaleCalibrate(calNum);
    calDigits = -1;
  }

  // --- drain packets handed over by the receive callback --------------------
  if (rxAckPending) {
    rxAckPending = false;
    ensureGatewayPeer((const uint8_t*)rxSrcMac);
    lastRssi     = rxRssiVal;
    lastPacketAt = now;
    if ((int)rxAckCupId != myCupId) {
      myCupId = rxAckCupId;
      Serial.printf("[link] assigned cup ID %d\n", myCupId);
    }
  }

  if (rxStatePending) {
    rxStatePending = false;
    ensureGatewayPeer((const uint8_t*)rxSrcMac);
    memcpy(&lastState, &rxStateBuf, sizeof(lastState));

    // Drop detection: any gap in seq is packets we missed. A seq lower than
    // the last one seen means the gateway rebooted — resync, don't count.
    if (haveSeq && lastState.seq > lastSeq + 1)
      droppedCount += lastState.seq - lastSeq - 1;
    lastSeq  = lastState.seq;
    haveSeq  = true;
    haveState = true;
    lastRssi     = rxRssiVal;
    lastPacketAt = now;
  }

  scaleTick(now);

  // --- uplink cadence --------------------------------------------------------
  if (myCupId < 0) {
    if (now - tHello >= HELLO_MS) {
      tHello = now;
      sendHello();
    }
  } else if (gatewayKnown && now - tTelemetry >= TELEMETRY_MS) {
    tTelemetry = now;
    sendTelemetry();
  }

  renderTick();
}
